# Generated by Django 3.2.5 on 2021-08-22 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='finish_time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
