# Generated by Django 3.2.5 on 2023-07-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230730_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(default=11, max_length=128),
            preserve_default=False,
        ),
    ]
